### ISSUE TITLE
Material UI Select Option not Working

### ISSUE THREAD

**Issue by chrisk8er** [LiveBy/react-leaflet-control#41]
anyone using Material UI here? I have a problem with Select Option from Material UI. the pop-up menu is not showing when I  tried using the default Select Option then trying to click it. except for native options. (https://material-ui.com/components/selects/#native-select)

https://imgur.com/m8w2YBb

**Comment by ghost** [comment]
Got similar problem but no solution yet. 

When I am using list with selectable options in drop-down, the control wont handle the shown dropdown list. When I select any item, it wont click on the selected item but on the map (can be easily verified by adding onClick to the map). However, this is not only problem with Material UI... the problem is with react-leaflet-control.

EDIT:

To solve this issue, see https://github.com/LiveBy/react-leaflet-control/issues/2#issuecomment-486981659
